language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.3
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q django-discover-runner
  - pip install -q mock>=1.0,<1.1 --use-mirrors
  - pip install coveralls
script:
  - coverage run --source=. run_tests.py
after_success:
  - coveralls